name: "PROD: Check, generate, and deploy (if push to master) xcsoar-data-content"

on: 
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #environment: production

    steps:
      - uses: actions/checkout@v2

      - name: "install requirements"
        run: |
          pip3 install -r requirements.txt

      - name: "Test PR"
        run: |
          ./script/deploy-test.bash
        if: github.event_name == 'pull_request'

      - name: "PROD: Deploy"
        run: |
          ./script/deploy.bash
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_KEY:  ${{ secrets.DEPLOY_KEY  }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
